dist: trusty
language: node_js
node_js:
- stable
before_script:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: rPqRTNT7M4tgiokcmdxOfWUp1JPA3pQZcQ52hOTLoaIn3px99x0jWu9rn+p8MPjZFaw3pE+ylUn64ydwVvfl8AucCyZTvUDR1CcHT8tavnjrzlBcvEHakZVkJ7gr+20EGx+cXx5gjenXeZjXPMd4m4Utqd5iq/eTYTQDM2aDQ3Euh2SUsE9+CyvgvE08JGeGJpcxcR9tLjgl3RurzQ2rawKyWKdlwywVA5dmlll+HzlcEUfEEP8CAz6IndfLCebveV8JQoKp5krXvt/7UOZU6IjTPMf3s/OLcadTHHKRYx22E6oTT4qrPuFSZ65xaRRN3CymM16nif1sUKWLbvHIkVyuXuPAAKpNpoh8gToY/MnMhGWm4nj/bvBXx0kBhe+/f2hibtqtRxqSPX55fBojMsG1I5X1XxvwdHzGSeauva29emhzUQiHfwz+4rduVB9j+jLiODujkbwmZKkVm48uOmghwG2ZzZfYpMu1mvNP+JVzwg/LsSzw7fJPB3xm7vpjBZpY2pdw4+EynnvNAUcRj10AKt9XoaoFLuwOb3iUX6P8ydRpD5hOLDi9XHkvhbeUWlhLaWJXoMCnlrDsQe/4Y8Pjw97jqXUNOPHekyrZ+snLZJtpXetYTt56DcXOX/kXVrcC9wZ1TFcx3NGN+ZdHAaD4sldsXyn8CmMCW8LlQ8Q=
  app: crytocurrency-tracker
  on:
    repo: TreborOB/crytocurrency_tracker
